POST http://localhost:3000/auth/login HTTP/1.1
content-type: application/json

{
      "login": "memod",
      "password": "sccret98"
}

#################################################################################

POST http://localhost:3000/auth/register HTTP/1.1
content-Type: application/json

{
      "first_name": "Mourad",
      "last_name": "EL CADI",
      "username": "modex98",
      "email": "mourad@mail.com",
      "password": "sccret98",
      "password_confirmation": "sccret98"
}

#################################################################################

DELETE http://localhost:3000/auth/logout HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjIwYjk2N2NhOGIyOTA2NGYwYTNmNTkiLCJ1c2VybmFtZSI6Im1vZGV4OTgiLCJpYXQiOjE2NDYzMjQwODcsImV4cCI6MTY0NjMyNDEwMn0.3ValdR0_ea0jv9SEN3EkEEWqcffwWuAJ0cqeC6BJRWQ



#################################################################################

PATCH  http://localhost:3000/user/verify/622133f9da917d285ef69ab2/4537 HTTP/1.1



#################################################################################

POST  http://localhost:3000/user/forgotpassword HTTP/1.1
content-Type: application/json

{
      "email": "mourad@mail.com"
}

#################################################################################

PATCH  http://localhost:3000/user/resetpassword/6220b967ca8b29064f0a3f59/1794 HTTP/1.1
content-Type: application/json

{
      "password": "secret98",
      "password_confirmation": "secret98"
}


#################################################################################

PATCH  http://localhost:3000/auth/refresh HTTP/1.1
X-REFRESH: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjIxMzNmOWRhOTE3ZDI4NWVmNjlhYjIiLCJ1c2VybmFtZSI6Im1lbW9kIiwiaWF0IjoxNjQ2NDkxMDEwLCJleHAiOjE2NDY1MzQyMTB9.1JBjXUwWTVEXcWkpBS_w2c8NTVQpXhWkKs2hJJ5bQqs



#################################################################################

GET  http://localhost:3000/user/me HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjIxMzNmOWRhOTE3ZDI4NWVmNjlhYjIiLCJ1c2VybmFtZSI6Im1vZGV4OTgiLCJpYXQiOjE2NDY0OTkwMzQsImV4cCI6MTY0NjUwMjYzNH0.ZkduZ0MOgXYGl_4SBV9obH8T3m3T8TaQen4gfifPMaU


#################################################################################

PATCH  http://localhost:3000/user/update HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjIxMzNmOWRhOTE3ZDI4NWVmNjlhYjIiLCJ1c2VybmFtZSI6Im1lbW9kIiwiaWF0IjoxNjQ2NDk1MzQ5LCJleHAiOjE2NDY0OTg5NDl9.pWOrK16jLCeKecc41CBecWC3GE8dEHzqCAYKCGHrR-c
content-Type: application/json

{
      "first_name": "Mourad",
      "last_name": "EL CADI",
      "username": "modex98",
      "email": "almod@hotmail.com"
}

#################################################################################

PATCH  http://localhost:3000/user/update/meta HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjIxMzNmOWRhOTE3ZDI4NWVmNjlhYjIiLCJ1c2VybmFtZSI6Im1vZGV4OTgiLCJpYXQiOjE2NDY1MDYwMDMsImV4cCI6MTY0NjUwOTYwM30.oEsYC07PDJwcx4Ll8eS4PSdlldE5k60cge45f1EPYsE
content-Type: application/json

{
      "phone_number": "+21261948806",
      "dob": "2020-04-40",
      "gender": false,
      "location": {
            "country": 5,
            "region": 6,
            "city": 1,
            "timezone": 3
      },
      "marital_status": 9,
      "height": 12,
      "weight": 9,
      "hair_color": 9,
      "eye_color": 53,
      "children": 9,
      "relegion": 3,
      "smoking": 0,
      "drinking": 1,
      "income": 9,
      "education": "University",
      "ocupation": "Programmer",
      "languages": [1, 9],
      "partner_age": {
            "from": 19,
            "to": 30
      },
      "about_me": "hard working and hopping fo good ...",
      "about_partner": "hard working and hopping fo good ..."
}

#################################################################################
/*

{
  "accessToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjIxMzNmOWRhOTE3ZDI4NWVmNjlhYjIiLCJ1c2VybmFtZSI6Im1vZGV4OTgiLCJpYXQiOjE2NDY1MDYwMDMsImV4cCI6MTY0NjUwOTYwM30.oEsYC07PDJwcx4Ll8eS4PSdlldE5k60cge45f1EPYsE",
  "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjIxMzNmOWRhOTE3ZDI4NWVmNjlhYjIiLCJ1c2VybmFtZSI6Im1lbW9kIiwiaWF0IjoxNjQ2NDkxMDEwLCJleHAiOjE2NDY1MzQyMTB9.1JBjXUwWTVEXcWkpBS_w2c8NTVQpXhWkKs2hJJ5bQqs"
}

*/