POST http://localhost:3000/auth/login HTTP/1.1
content-type: application/json

{
      "login": "modex98",
      "password": "sccret98"
}

#################################################################################

POST http://localhost:3000/auth/register HTTP/1.1
content-Type: application/json

{
      "first_name": "Mourad",
      "last_name": "EL CADI",
      "username": "modex98",
      "email": "mourad@mail.com",
      "password": "sccret98",
      "password_confirmation": "sccret98"
}

#################################################################################

DELETE http://localhost:3000/auth/logout HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjIwYjk2N2NhOGIyOTA2NGYwYTNmNTkiLCJ1c2VybmFtZSI6Im1vZGV4OTgiLCJpYXQiOjE2NDYzMjQwODcsImV4cCI6MTY0NjMyNDEwMn0.3ValdR0_ea0jv9SEN3EkEEWqcffwWuAJ0cqeC6BJRWQ



#################################################################################

PATCH  http://localhost:3000/user/verify/6220b967ca8b29064f0a3f59/3611 HTTP/1.1



#################################################################################

POST  http://localhost:3000/user/forgotpassword HTTP/1.1
content-Type: application/json

{
      "email": "mourad@mail.com"
}

#################################################################################

PATCH  http://localhost:3000/user/resetpassword/6220b967ca8b29064f0a3f59/1794 HTTP/1.1
content-Type: application/json

{
      "password": "secret98",
      "password_confirmation": "secret98"
}


#################################################################################

PATCH  http://localhost:3000/auth/refresh HTTP/1.1
X-REFRESH: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjIwYjk2N2NhOGIyOTA2NGYwYTNmNTkiLCJ1c2VybmFtZSI6Im1vZGV4OTgiLCJpYXQiOjE2NDYzMjM5MjcsImV4cCI6MTY0NjMyMzk4N30.qm3bes6QA-vc8fY_2TXwOetftA9OwNPt8ul9rfnFaYY
